name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - master
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  TBD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0